version: "3.8"

services:
  postgres:
    image: postgres # hub.docker.com
    ports:  #port mapping
      - "5432:5432" 
    environment:  #env variables
      POSTGRES_USER: postgres
      POSTGRES_DB: review
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - "6379:6379"
